# Generated by Django 5.1.4 on 2025-01-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clausula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('numero_contrato', models.CharField(max_length=100, unique=True)),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('objeto', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('terminos', models.TextField()),
            ],
            options={
                'db_table': 'content_contrato',
            },
        ),
    ]
